<GameData.Role.ExpLevel Ver="0">
	<Id Type="mscorlib.dll@System.Byte" Value="1"/>
	<Name Type="mscorlib.dll@System.String" Value="aaa"/>
	<Version Type="mscorlib.dll@System.UInt32" Value="2"/>
	<RoleMaxLevel Type="mscorlib.dll@System.UInt16" Value="18"/>
	<LevelExps Type="mscorlib.dll@System.Collections.Generic.List`1[[mscorlib.dll@System.Int64]]"/>
	<DeathProvideExps Type="mscorlib.dll@System.Collections.Generic.List`1[[mscorlib.dll@System.Int64]]"/>
</GameData.Role.ExpLevel>

